title: Navigating Stories
email: k.pijpers@utwente.nl
description: This project aims to develop eScience technologies to advance multidisciplinary approaches of digital storytelling.
#baseurl: ""
#url: "https://navigating-stories.github.io/notebooks/"
#repository: "navigating-stories/notebooks"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
minimal_mistakes_skin: "dirt" # "default", "air", "aqua", "dark", "contrast", "sunrise", "neon", "mint" "plum"
permalink: /:categories/:title/
#paginate: 5 
#paginate_path: /page:num/
show_excerpts: true
search: true
timezone: Europe/Amsterdam

include:
  - _pages

plugins:
#  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-algolia

author: 
  name: "Storylab"
  subtitle: "Department of Psychology, Health and Technology
            > University of Twente"
  avatar: 
  location: "Enschede, the Netherlands"
  links :
    - label: "Story Lab - University of Twente"
      icon: "fas fa-fw fa-link"
      url: "https://www.utwente.nl/en/bms/ehealth/research/story-lab/"
    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/lab/StoryLab-Gerben-J-Westerhof"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/verhalenlab"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/navigating-stories/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      read_time: true
      share: true
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
